{{ if .Values.postgres.enabled }}
# Source: airflow/charts/postgresql/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "postgresql-{{ .Release.Namespace }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "postgresql-{{ .Release.Namespace }}"
spec:
  serviceName: postgresql-headless-{{ .Release.Namespace }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "postgresql-{{ .Release.Namespace }}"
  template:
    metadata:
      name: "postgresql-{{ .Release.Namespace }}"
      labels:
        app: "postgresql-{{ .Release.Namespace }}"
    spec:
      containers:
        - name: postgresql-{{ .Release.Namespace }}
          image: postgres:15.3
          imagePullPolicy: "IfNotPresent"
          resources:
{{ toYaml .Values.postgres.resources | indent 12 }}
          env:
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ .Release.Namespace }}-password
                  key: postgresql-password
            - name: POSTGRES_DB
              value: "airflow"
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
          ports:
            - name: airflow
              containerPort: 5432
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "postgres" -d "airflow" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "postgres" -d "airflow" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
{{ end }}
