################################
## Airflow Pod Launcher Role
#################################
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-pod-launcher-role-{{ .Values.env }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "create"
      - "list"
      - "get"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
