################################
## Airflow Pod Reader Role
#################################
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-pod-log-reader-role-{{ .Values.env }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
      - "list"
