apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-run-airflow-migrations-{{ .Values.env }}
  namespace: "{{ .Release.Namespace }}"
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        tier: airflow
        component: run-airflow-migrations
        release: {{ .Chart.Name }}
    spec:
      securityContext:
          runAsUser: 50000
      restartPolicy: OnFailure
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      serviceAccountName: {{ .Chart.Name }}-{{ .Values.env }}
      containers:
        - name: run-airflow-migrations
          image: {{ template "airflow_image" . }}
          imagePullPolicy: IfNotPresent
          # Support running against 1.10.x and 2.x
          args:
            - bash
            - -c
            - |-
              exec \
              airflow db upgrade
          envFrom:
            []
          env:
          {{- include "standard_airflow_environment" . | indent 10 }}
          volumeMounts:
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
          resources:
            {}
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}-airflow-config-{{ .Values.env }}
---
################################
## Airflow Create User Job
#################################
kind: Job
apiVersion: batch/v1
metadata:
  name: {{ .Chart.Name }}-create-user-{{ .Values.env }}
  namespace: "{{ .Release.Namespace }}"
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        tier: airflow
        component: create-user-job
        release: {{ .Chart.Name | quote }}
    spec:
      securityContext:
          runAsUser: 50000
      restartPolicy: OnFailure
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      serviceAccountName: {{ .Chart.Name }}-{{ .Values.env }}
      containers:
        - name: create-user
          image: {{ template "airflow_image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - "bash"
            - "-c"
            - 'airflow users create "$@"'
            - --
            - "-r"
            - Admin
            - "-u"
            - admin
            - "-e"
            - admin@example.com
            - "-f"
            - admin
            - "-l"
            - admin
            - "-p"
            - admin
          envFrom:
            []
          env:
          {{- include "standard_airflow_environment" . | nindent 10 }}
          volumeMounts:
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
          resources:
            {}
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}-airflow-config-{{ .Values.env }}
