################################
## Airflow Redis Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: "redis-{{ .Release.Namespace }}"
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: redis
    release: {{ .Chart.Name }}
  ports:
    - name: redis-db
      protocol: TCP
      port: 6379
      targetPort: 6379
