apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dag-data-{{ .Values.env }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
