apiVersion: v1
kind: PersistentVolume
metadata:
  name: dag-data-{{ .Values.env }}-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/airflow/data-pipeline
