kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}-scheduler-{{ .Values.env }}
  namespace: "{{ .Release.Namespace }}"
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  strategy:
    # Kill the scheduler as soon as possible.
    # It will restart quickly with all the workers, minimizing the time they are not synchronized.
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  selector:
    matchLabels:
      tier: airflow
      component: scheduler
      release: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        tier: airflow
        component: scheduler
        release: {{ .Chart.Name }}
    spec:
      nodeSelector:
        {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  component: scheduler
              topologyKey: kubernetes.io/hostname
            weight: 100
      tolerations:
        []
      topologySpreadConstraints:
        []
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ .Chart.Name }}-{{ .Values.env }}
      securityContext:
        runAsUser: 50000
        fsGroup: 0
      initContainers:
        - name: wait-for-airflow-migrations
          resources:
            {}
          image: {{ template "airflow_image" . }}
          imagePullPolicy: Never
          volumeMounts:
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
            - name: config
              mountPath: "/opt/airflow/config/airflow_local_settings.py"
              subPath: airflow_local_settings.py
              readOnly: true
          args:
            - airflow
            - db
            - check-migrations
            - --migration-wait-timeout=60
          envFrom:
            []
          env:
            {{- include "standard_airflow_environment" . | indent 10 }}
      containers:
        - name: scheduler
          image: {{ template "airflow_image" . }}
          imagePullPolicy: Never
          args:
            - bash
            - -c
            - exec airflow scheduler
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          envFrom:
            []
          env:
            - name: AIRFLOW__METRICS__STATSD_PORT
              value: "8125"
            - name: AIRFLOW__METRICS__STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- include "standard_airflow_environment" . | indent 10 }}
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 20
            failureThreshold: 5
            periodSeconds: 60
            exec:
              command:
                  - sh
                  - -c
                  - |
                    CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \
                    airflow jobs check --job-type SchedulerJob --hostname $(hostname)
          volumeMounts:
            - name: logs
              mountPath: /opt/airflow/logs
            - name: config
              mountPath: /opt/airflow/pod_templates/pod_template_file.yaml
              subPath: pod_template_file.yaml
              readOnly: true
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
            - name: config
              mountPath: "/opt/airflow/config/airflow_local_settings.py"
              subPath: airflow_local_settings.py
              readOnly: true
            - name: dag-data
              mountPath: /opt/airflow/dags
              readOnly: true
        - name: scheduler-log-groomer
          resources:
            requests:
              {}
          image: {{ template "airflow_image" . }}
          imagePullPolicy: Never
          args:
            - bash
            - /clean-logs
          env:
            - name: AIRFLOW__LOG_RETENTION_DAYS
              value: "15"
          volumeMounts:
            - name: logs
              mountPath: "/opt/airflow/logs"
      volumes:
        - name: logs
          emptyDir: {}
        - name: config
          configMap:
            name: airflow-config-{{ .Values.env }}
            defaultMode: 0755
        - name: dag-data
          persistentVolumeClaim:
            claimName: "dag-syncer-pvc-{{ .Values.env }}"
