
apiVersion: v1
kind: Secret
metadata:
  name: webserver-key
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  webserver-key: "b46f1a10f3eed7a79540729f34a7da37"
