env: ~

# image of airflow
images:
  airflow:
    repository: "data_undercurrents/airflow"
    tag: "1.0.0"
  statsd:
    repository: quay.io/prometheus/statsd-exporter
    tag: v0.22.8
    pullPolicy: IfNotPresent
  pgbouncer:
    repository: apache/airflow
    tag: airflow-pgbouncer-2023.02.24-1.16.1
    pullPolicy: IfNotPresent
  pgbouncerExporter:
    repository: apache/airflow
    tag: airflow-pgbouncer-exporter-2023.02.21-0.14.0
    pullPolicy: IfNotPresent
  gitSync:
    repository: registry.k8s.io/git-sync/git-sync
    tag: v3.6.3
    pullPolicy: IfNotPresent
# default k8s object label
labels:
  app: "data-pipeline"

# dag file processor
dagProcessor:
  # Whether the dag processor is running as a standalone process or it is a subprocess of a scheduler job.
  enabled: ~
  resources: {}
  updateDag:
    resources: ~
  annotations: {}

scheduler:
  resources:
    requests:
      cpu: ~
      memory: ~
    limits:
      cpu: ~
      memory: ~

# airflow triggerer
triggerer:
  enabled: ~
  resources:
    requests:
      cpu: ~
      memory: ~
    limits:
      cpu: ~
      memory: ~

# airflow config
webserver:
  ingress:
    name: ~
    annotations: ~
    labels:
      app: data-pipeline
  resources:
    requests:
      cpu: ~
      memory: ~
    limits:
      cpu: ~
      memory: ~

gitSync:
  enabled: ~
  repo: ~
  branch: ~
  rev: ~
  depth: ~
  maxFailures: ~
  subPath: ~


# airflow metadata db in k8s cluster (postgres)
postgres:
  enabled: ~
  postgresPassword: ~
  resources: {}

# main db in k8s cluster (postgres)
postgresMainDB:
  enabled: ~
  postgresPassword: ~
  resources: {}

# Airflow job to create a user settings for the webserver
createUserJob:
  enabled: ~

# airflow.cfg
# https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html
airflowCfg: ~

# airflow webserver config related web authentication, warning, sensitive variables fields and others
# https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html
webserverConfig: ~

# airflow local settings py override
# https://airflow.apache.org/docs/apache-airflow/stable/howto/customize-ui.html
airflowLocalSettings: ~
