################################
## Airflow Metadata Secret
#################################
apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata
  namespace: "{{ .Release.Namespace }}"
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  connection: {{ (include "airflow_db_conn" .) | b64enc | quote }}
