################################
## Airflow Fernet Key Secret
#################################

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-fernet-key
  namespace: "{{ .Release.Namespace }}"
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  fernet-key: "V21rMlZEUkRRM05HU0dScU9HaDZUSEZWVVVKSlFVeEJaMHRrYkVJMVdFYz0="
