{{ if .Values.postgres.enabled }}
{{ if .Values.postgres.postgresPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: "postgresql-{{ .Release.Namespace }}-password"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Namespace }}"
type: Opaque
data:
  postgresql-password: {{ .Values.postgres.postgresPassword | b64enc | quote }}
{{ end }}
{{ end }}
