{{ if .Values.postgresMainDB.enabled }}
{{ if .Values.postgresMainDB.postgresPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: "postgresql-maindb-{{ .Release.Namespace }}-password"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Namespace }}"
type: Opaque
data:
  postgresql-maindb-password: {{ .Values.postgresMainDB.postgresPassword | b64enc | quote }}
{{ end }}
{{ end }}
