################################
## Airflow StatsD Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: "statsd-{{ .Release.Namespace }}"
  labels:
    app: "statsd-{{ .Release.Namespace }}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
spec:
  type: ClusterIP
  selector:
    app: "statsd-{{ .Release.Namespace }}"
  ports:
    - name: statsd-ingest
      protocol: UDP
      port: 9125
      targetPort: 9125
    - name: statsd-scrape
      protocol: TCP
      port: 9102
      targetPort: 9102
