apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redash.fullname" . }}
  labels:
    {{- include "redash.labels" . | nindent 4 }}
type: Opaque
data:
  cookieSecret: {{ randAlphaNum 50 | b64enc | quote }}
  secretKey: {{ randAlphaNum 50 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}
