apiVersion: v1
kind: PersistentVolume
metadata:
  name: dag-syncer-pv-{{ .Values.env }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  storageClassName: "dag-syncer"
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/airflow/dags"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dag-syncer-pvc-{{ .Values.env }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  storageClassName: "dag-syncer"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
